apiVersion: skaffold/v2beta26
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: artifactory.maaii.com/lc-docker-local/go-project-template-SKAFFOLD_SUFFIX
    docker:
      buildArgs:
        APPNAME: go-project-template
      dockerfile: devops/Dockerfile
      cliFlags:   
      - --platform=linux/amd64
  local:
    useDockerCLI: true

deploy:
  kustomize: 
    paths: 
    - devops/
