[app]
namespace = "dev-hk-03"
prof = false

[http]
api_timeout = "15s"
mode = "debug"
port = "8082"
read_timeout = "40s"
write_timeout = "40s"

[log]
# Discard means not write log to local file
# output = "Discard"
output = "Stdout"
# output = "test.log"
access_level = "trace"
level = "debug"
timestamp_format = ""

[otel.traces]
sampler_arg = 1

[kafka]
bootstrap_servers = "dev-hk-db62.cloud.maaii.local:9092,dev-hk-db63.cloud.maaii.local:9092,dev-hk-db64.cloud.maaii.local:9092"
sasl_mechanism = "PLAIN"
sasl_password = "kafka-lcc5"
sasl_username = "lcc5"
security_protocol = "sasl_ssl"
ssl_ca_location = "devkafkaca.crt"
# producer
acks = -1
enable_idempotence = true
events_channel_size = 1048576
go_batch_producer = false
produce_channel_size = 1048576

[database]
[database.mgo]
authdatabase = "admin"
direct = false
hosts = "localhost:27017"
max_conn = 4
max_idle = 15
mongos = false
name = "admin"
password = "secret"
secondary = false
timeout = "30s"
user = "admin"

[database.redis]
connect_timeout = "5s"
host = "172.30.3.146:26379;172.30.3.36:26379;172.30.3.161:26379"
idle_timeout = "180s"
master = "lcc5-hk-dev-master"
max_active = 20
max_idle = 3
password = "fXC7tLD57bGRYDVM"
sentinel_password = "nm2ZWZrLQ9F8Sw2N"
