{
 "title": "Labeled Metrics Sample Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Service",
    "label": "Service",
    "query": "label_values(go_project_template_labeled_counter_total, service)"
   },
   {
    "name": "Type",
    "label": "Type",
    "query": "label_values(go_project_template_labeled_counter_total{service=~\"$Service\"}, type)"
   }
  ]
 },
 "panels": [
  { "title": "Counter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Counter (by service)",
   "type": "graph",
   "description": "sum (rate(go_project_template_labeled_counter_total[$__interval])) by (service)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(go_project_template_labeled_counter_total{service=\"service1\"}[1m])) by (service)"
    }
   ]
  },
  {
   "title": "Counter (by type)",
   "type": "graph",
   "description": "sum (rate(go_project_template_labeled_counter_total[$__interval])) by (type)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(go_project_template_labeled_counter_total[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last score of English test",
   "type": "gauge",
   "description": "go_project_template_labeled_gauge_latest_value",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "go_project_template_labeled_gauge_latest_value",
     "legendFormat": "{{service}}-{{type}}"
    }
   ]
  },
  {
   "title": "Last score of English test ( service 1 )",
   "type": "table",
   "description": "go_project_template_labeled_gauge_latest_value{service=\"service1\"}",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "go_project_template_labeled_gauge_latest_value{service=\"service1\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Histogram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "histogram_data_value_bucket (count)",
   "type": "heatmap",
   "description": "go_project_template_labeled_histogram_data_value_bucket{service=~\"$Service\", type=~\"$Type\"} - go_project_template_labeled_histogram_data_value_bucket{service=~\"$Service\", type=~\"$Type\"} offset $__interval",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "go_project_template_labeled_histogram_data_value_bucket{service=~\"$Service\", type=~\"$Type\"} - go_project_template_labeled_histogram_data_value_bucket{service=~\"$Service\", type=~\"$Type\"} offset $__interval",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Histogram quantile",
   "type": "graph",
   "description": "histogram_quantile(0.5, sum by (service, type, le)(rate(go_project_template_labeled_histogram_data_value_bucket{service=~\"$Service\", type=~\"$Type\"}[$__interval])))",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (service, type, le)(rate(go_project_template_labeled_histogram_data_value_bucket{service=~\"$Service\", type=~\"$Type\"}[$__interval])))",
     "legendFormat": "quantile - 0.5 | {{service}} - {{type}}"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Summary quantile",
   "type": "graph",
   "description": "rate(go_project_template_labeled_summary_data_value{service=~\"$Service\", type=~\"$Type\", quantile=\"0.8\"}[$__interval])",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_project_template_labeled_summary_data_value{service=~\"$Service\", type=~\"$Type\", quantile=\"0.8\"}[$__interval])",
     "legendFormat": "Quantile - 0.8 | {{service}} - {{type}}"
    },
    {
     "expr": "rate(go_project_template_labeled_summary_data_value{service=~\"$Service\", type=~\"$Type\", quantile=\"0.5\"}[$__interval])",
     "legendFormat": "Quantile - 0.5 | {{service}} - {{type}}"
    }
   ]
  }
 ]
}