{
 "title": "Metrics Sample Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Counter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Counter",
   "type": "graph",
   "description": "rate(go_project_template_counter_total[$__interval])",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_project_template_counter_total[$__interval])",
     "legendFormat": "Counter"
    }
   ]
  },
  { "title": "Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last score of English test",
   "type": "gauge",
   "description": "go_project_template_gauge_latest_value",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "go_project_template_gauge_latest_value"
    }
   ]
  },
  {
   "title": "Last score of English test",
   "type": "table",
   "description": "go_project_template_gauge_latest_value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "go_project_template_gauge_latest_value"
    }
   ]
  },
  { "title": "Histogram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "histogram_data_value_bucket (count)",
   "type": "heatmap",
   "description": "go_project_template_histogram_data_value_bucket - go_project_template_histogram_data_value_bucket offset $__interval",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "go_project_template_histogram_data_value_bucket - go_project_template_histogram_data_value_bucket offset $__interval",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Histogram quantile",
   "type": "graph",
   "description": "histogram_quantile(0.5, sum by (le)(rate(go_project_template_histogram_data_value_bucket[$__interval])))",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(go_project_template_histogram_data_value_bucket[$__interval])))",
     "legendFormat": "quantile - 0.5"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Summary quantile",
   "type": "graph",
   "description": "rate(go_project_template_summary_data_value{quantile=\"0.8\"}[$__interval])",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_project_template_summary_data_value{quantile=\"0.8\"}[$__interval])",
     "legendFormat": "quantile - 0.8"
    },
    {
     "expr": "rate(go_project_template_summary_data_value{quantile=\"0.5\"}[$__interval])",
     "legendFormat": "quantile - 0.5"
    }
   ]
  }
 ]
}