[http]
  port = "8999"
  read_timeout = "40s"
  write_timeout = "40s"
  client_timeout = "15s"
  mode = "debug"

[log]
  # Discard means not write log to local file
  # file_name = "Discard"
  file_name = "Stdout"
  # file_name = "test.log"
  level = "info"
  timestamp_format = ""
  access_level = "debug"

[jaeger]
  enabled = true
  host = "maaii-jaeger-agent"
  port = 6831
  sample_rate = 1
  queue_size = 128
  flush_interval = "10s"
  log_spans = false

[database]
[database.mgo.default]
  name = "Dev"
  user = "maaii"
  password = "@maaii"
  authdatabase = "admin"
  max_conn = 4
  max_idle = 15
  host_num = 1
  timeout = "30s"
  direct = true
  secondary = false
  mongos = false
[database.mgo.instance.0]
  host = "192.168.118.173"
  port = 27017
  enabled = true