apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-project-template
spec:
  template:
    spec:
      containers:
        - name: go-project-template
          env:
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "jaeger-collector:14268"
