apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-project-template
spec:
  template:
    spec:
      containers:
        - name: go-project-template
          env:
            # Reference: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md
            - name: OTEL_EXPORTER_JAEGER_PROTOCOL
              value: "udp/thrift.binary"
            - name: OTEL_TRACES_SAMPLER_ARG # Sample rate
              value: "1"
